
Usage: make options...

Option            Description
------            -----------
clean             Clean build directories of projects
build             Build projects with tests and quality checking
release           Create a new release from master branch
publish           Publish the latest version to Maven central

