---------------------------------------------------------------------
Usage: make clean|build|release|install|publish|deploy"

  clean   - clean the build folders
  build   - build the projects
  release - create a new release of gwt-uploader-core
  install	- install the current Maven artifacts into local maven
  publish - publish the latest stable release of gwt-uploader-core
            to Maven central
  deploy  - deploy gwt-upload-demo to remote AppEngine

---------------------------------------------------------------------
